# Only for Development
# 仅用于开发环境

name: uniboard-dev

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniboard-server
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./service:/app/service
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider --quiet http://localhost:8080/api/system-config" ]

  postgres:
    image: postgres:17.4-bookworm
    container_name: uniboard-dev-db
    environment:
      POSTGRES_DB: uniboard
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 10s
      retries: 10
