version: '3'
services:
  app:
    build: .
    networks:
      - network-UniBoard
    volumes:
      - ./.env:/app/UniBoard-Service/.env
      - ./config.json:/app/UniBoard-Service/config.json
      - ./data:/app/UniBoard-Service/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
    - "8000:8000"
  redis:
    image: redis
    networks:
      - network-UniBoard
networks:
  network-UniBoard: