version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: XFdWwID02qJxerertfTrYFiok7G1bg  # 设置Postgres密码
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    command: [ "redis-server", "--requirepass", "GdlkOVEmA3vp8JA6ZoAiqIPxSwZR5" ]  # 设置Redis密码
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
